sudo: required
dist: trusty
language: node_js
node_js:
  - '9'
  - '8'
  - '7'
  - '6'
services:
  - redis-server
env:
  # Can't figure out how to DRY this up: http://stackoverflow.com/q/22397300/3191
  - WEB_SERVER=express DATABASE=redis
  - WEB_SERVER=koa DATABASE=redis
matrix:
  exclude:
  - node: 6
    env: WEB_SERVER=koa DATABASE=redis
after_success:
  - npm run coverage:unit
  - npm run coveralls
