jasmine.DEFAULT_TIMEOUT_INTERVAL = 15000;

process.env.QEWD_STARTED_TIMEOUT = 1000;
process.env.EXIT_TIMEOUT = 1000;
process.env.MICROSERVICES_STARTED_TIMEOUT = 5000;
process.env.SOCKET_MESSAGING_MESSAGE_TIMEOUT = 3000;
process.env.SOCKET_MESSAGING_EXPECT_TIMEOUT = 6000;
